@authentication_app_HostAddress = https://localhost:44383
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRlc3QiLCJlbWFpbCI6ImwuYS5mZXJyZXRlQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTc0NTAxMjQwNiwiZXhwIjoxNzQ1MDEzMzA2LCJpYXQiOjE3NDUwMTI0MDYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjQ0MzgzIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzODMifQ.3or45Mc2TWYTrIVoluYjJf51L91EYwgH5rm6J9bieLE

POST {{authentication_app_HostAddress}}/user/
Content-Type: application/json
Accept: application/json

{
  "username": "t",
  "password": "pass123",
  "email": "l.a.ferrete@gmail.com"
}

###

POST {{authentication_app_HostAddress}}/user/changepassword
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json
{
  "oldPassword": "pass123",
  "newPassword": "Passw123@"
}

###

POST {{authentication_app_HostAddress}}/auth/login/
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "pass123"
}

###
POST {{authentication_app_HostAddress}}/auth/refresh
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "testetsetststeststst"
}

###
POST {{authentication_app_HostAddress}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{token}}